name: Test Runner
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Runner info
        run: |
          echo "Runner info"
          whoami
          hostname
          echo $RUNNER_NAME
