name: Build and Push Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          cd app
          docker build -t ghcr.io/${{ github.repository }}/web:latest .
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            docker tag ghcr.io/${{ github.repository }}/web:latest ghcr.io/${{ github.repository }}/web:pr-${{ github.event.number }}
          fi

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/web:latest
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            docker push ghcr.io/${{ github.repository }}/web:pr-${{ github.event.number }}
          fi
