name: Cleanup PR
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Remove preview
        run: |
          bash scripts/remove_preview.sh ${{ github.event.number }}