name: Deploy Base / PR Preview

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_closed:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy base site
        if: github.ref == 'refs/heads/main'
        run: |
          cd scripts
          bash deploy_base.sh

      - name: Deploy PR preview
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        run: |
          PR_NUM=${{ github.event.number }}
          PORT=$((30000 + PR_NUM))
          cd scripts
          bash deploy_preview.sh $PR_NUM $PORT

      - name: Remove PR preview on close
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          PR_NUM=${{ github.event.number }}
          cd scripts
          bash remove_preview.sh $PR_NUM
          