version: '3.8'

services:
  react-app-main:
    image: ghcr.io/faraheloumi/pr-preview-project-react-nginx/web:latest
    container_name: react-app-main
    networks:
      - webnet

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
