version: '3.8'

services:
  react-app:
    #build: ./react-app
    image: ghcr.io/faraheloumi/pr-preview-project-react-nginx/web:latest
    container_name: pr-pipeline-project-container
    ports:
    #expose:
      - "3000:80"      
    networks:
      - pr-preview-net

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy-duckdns
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
        
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
    networks:
      - pr-preview-net

  # certbot:
  #   image: certbot/certbot:latest
  #   container_name: certbot
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #   networks:
  #     - pr-preview-net

networks:
  pr-preview-net:
