version: '3.8'

services:
  react-app-main:
    image: ghcr.io/faraheloumi/pr-preview-project-react-nginx/web:latest
    container_name: react-app-main
    networks:
      - webnet

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    volumes:
      - ./certs:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./certbot-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    networks:
      - webnet
    depends_on:
      - nginx-proxy
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/certbot
      - --email
      - farah.elloumi2000@gmail.com
      - --agree-tos
      - --no-eff-email
      - -d
      - farahelloumi.duckdns.org
      - --non-interactive

networks:
  webnet:
    name: webnet
    driver: bridge