name: Build and Push Docker Images
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      GITHUB_EVENT_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push
        shell: powershell
        run: |
          $IMAGE = "ghcr.io/${{ github.repository }}/web"

          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $TAG = "pr-$env:GITHUB_EVENT_NUMBER"
          } else {
            $TAG = "latest"
          }

          docker build -t "${IMAGE}:latest" ./app
          docker tag "${IMAGE}:latest" "${IMAGE}:${TAG}"
          docker push "${IMAGE}:latest"
          docker push "${IMAGE}:${TAG}"