name: Build and Push Docker Images
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      - name: Build & Push
        shell: bash
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/web
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            TAG=pr-${{ github.event.number }}
          else
            TAG=latest
          fi
          docker build -t $IMAGE:latest ./app
          docker tag $IMAGE:latest $IMAGE:$TAG
          docker push $IMAGE:latest
          docker push $IMAGE:$TAG
