name: Deploy Base and PR Previews

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      EVENT_NAME: ${{ github.event.workflow_run.event }}
      PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Deploy
        shell: powershell
        run: |
          if ($env:EVENT_NAME -eq "push") {
            ./scripts/deploy_base.ps1
          } elseif ($env:EVENT_NAME -eq "pull_request") {
            ./scripts/deploy_preview.ps1 $env:PR_NUMBER
          }