name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        shell: bash
        run: |
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            pwsh ./scripts/deploy_base.ps1
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            if [ "$GITHUB_EVENT_ACTION" = "closed" ]; then
              pwsh ./scripts/remove_preview.ps1 $GITHUB_EVENT_NUMBER
            else
              pwsh ./scripts/deploy_preview.ps1 $GITHUB_EVENT_NUMBER
            fi
